id: P08942888
initial_creation_type: input
source_metadata:
  title: Shakya Shri Series
  language: zh
  description: 'Texts by the great yogi Tokden Shakya Shri (rtogs ldan shākya shrī,
    1853–1919):'
  volume:
    505b7b6566d04fc7aa510bd217c64c85:
      title: 'A Shower of Blessings: A Guru Yoga Practice to Accompany the Seven Line
        Prayer (Addendum)'
      parent: Guru Yoga
    d166375f859f443d8f47008362640cbe:
      title: Supplication to Lord Mila Shepa Dorje
      parent: Prayers
    e2ca57251b0a4201bcd41a155d43ea44:
      title: 'The Shower of Blessings: A Prayer'
      parent: Prayers
created_at: '2022-03-01T01:32:11.871315'
last_modified_at: '2022-03-01T01:32:11.871318'
